# version: '3.8'

# services:
#     back_end:
#         image: chayanpx/final-backend:1.0.0
#         ports:
#             - 4141:3000
#         environment:
#             - PORT=3000
#             - MODE=DEV
#             - POSTGRES_HOST=206.189.38.174
#             - POSTGRES_PORT=15432
#             - POSTGRES_USER=postgres
#             - POSTGRES_PASSWORD=EE71D5DCCFA3A
#             - POSTGRES_DATABASE=postgres
#             - POSTGRES_SYNC="false"
#             - POSTGRES_DROP_SCHEMA="false"
#     front_end:
#         image: chayanpx/final-frontend:1.0.0
#         ports:
#             - 1414:80