// pipeline {
//     agent any
//     stages {
//         stage('Pull code') {
//             steps {
//                 git branch: 'main', url: 'https://github.com/chayanpx/three-magic-hour-final.git'
//             }
//         }
//         stage('Download dependency') {
//             steps {
//                 dir('./back-end'){
//                     sh 'yarn install'
//                 }
//             }
//         }
//         stage('Run unit test and Generate unit test report') {
//             steps {
//                 dir('./back-end') {
//                     sh 'yarn run test:cov'
//                 }
//             }
//         }
//         stage('Run component test and Generate component test report') {
//             steps {
//                 dir('./back-end') {
//                     sh 'yarn run test:component:cov'
//                 }
//             }
//         }
//         stage('Build and Deploy') {
//             steps {
//                 withCredentials([string(credentialsId: 'backend-server', variable: 'HOST'), string(credentialsId: 'team-14-username', variable: 'USERNAME'), string(credentialsId: 'team-14-password', variable: 'PASSWORD')]) {
//                     script {
//                         def remote = [:]
//                         remote.name = "team-14-backend"
//                         remote.host = "${HOST}"
//                         remote.user = "${USERNAME}"
//                         remote.password = "${PASSWORD}"
//                         remote.allowAnyHosts = true
//                         sshCommand remote: remote, command: "git clone -b main https://github.com/pspapleng/Project-SW-dev-tool-env-14.git team-14-backend"
//                         sshCommand remote: remote, command: "cd team-14-backend && VERSION=\$(git describe --tags --abbrev=0) docker-compose -f ./docker-compose-build.yaml build back_end"
//                         sshCommand remote: remote, command: "cd team-14-backend && VERSION=\$(git describe --tags --abbrev=0) docker-compose -f ./docker-compose-deploy.yaml up -d back_end"
//                         sshCommand remote: remote, command: "rm -r team-14-backend"
//                     }    
//                 }     
//             }
//         }         
//         stage('Test Backend') {
//             steps {
//                 sleep time: 30, unit: 'SECONDS'
//                 sh "curl http://159.223.45.216:4141/"
//             }
//         }
//         stage('Run E2E test and Generate E2E test report') {
//             steps {
//                 dir('./back-end') {
//                     sh 'yarn run test:e2e:cov'
//                 }
//             }
//         }
//     }
// }